feat: Ollama setup added

diff --git a/deploy/Dockerfile b/deploy/Dockerfile
--- a/deploy/Dockerfile
+++ b/deploy/Dockerfile
@@ -1,6 +1,6 @@
 # syntax=docker.io/docker/dockerfile:1
 
-FROM node:22-alpine AS base
+FROM ubuntu:latest AS base
 
 
 # Add build arguments
@@ -32,6 +32,25 @@ ENV DOCKER_PRIVYIO_APP_ID=${PRIVYIO_APP_ID}
 ENV DOCKER_PRIVYIO_APP_SECRET=${PRIVYIO_APP_SECRET}
 
 
+# Update apt-get and install all the required packages
+RUN apt-get update && \
+    apt-get install -y curl && \
+    apt-get install -y build-essential python3 make g++ && \
+    apt-get clean && rm -rf /var/lib/apt/lists/*
+
+# Install NVM (Node Version Manager)
+RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
+
+# Copy .nvmrc file
+COPY .nvmrc /root/.nvmrc
+
+# Install Node.js version specified in .nvmrc
+RUN bash -c '. "/root/.nvm/nvm.sh" && nvm install $(cat /root/.nvmrc) && nvm use $(cat /root/.nvmrc)'
+
+# Install Pnpm globally
+RUN bash -c '. "/root/.nvm/nvm.sh" && npm install -g pnpm'
+
+
 # Contracts dependencies stage
 # Install dependencies only when needed
 FROM base AS contracts-deps
@@ -39,29 +58,29 @@ WORKDIR /contracts
 
 # Install dependencies based on the preferred package manager
 COPY contracts/package.json contracts/yarn.lock* contracts/package-lock.json* contracts/pnpm-lock.yaml* contracts/.npmrc* ./
-RUN \
+RUN bash -c '\
+  . "/root/.nvm/nvm.sh" && \
   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
   elif [ -f package-lock.json ]; then npm ci; \
   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
   else echo "Lockfile not found." && exit 1; \
-  fi
+  fi'
 
 
 # Teesa dependencies stage
 # Install dependencies only when needed
 FROM base AS teesa-deps
-# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
-RUN apk add --no-cache libc6-compat python3 make g++
 WORKDIR /teesa
 
 # Install dependencies based on the preferred package manager
 COPY teesa/package.json teesa/yarn.lock* teesa/package-lock.json* teesa/pnpm-lock.yaml* teesa/.npmrc* ./
-RUN \
+RUN bash -c '\
+  . "/root/.nvm/nvm.sh" && \
   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
   elif [ -f package-lock.json ]; then npm ci; \
   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
   else echo "Lockfile not found." && exit 1; \
-  fi
+  fi'
 
 
 # Build stage
@@ -95,7 +114,7 @@ RUN cd ./teesa && \
 
 # Deploy the contract
 RUN cd ./contracts && \
-    npx hardhat compile-contract && \
+    bash -c '. "/root/.nvm/nvm.sh" && npx hardhat compile-contract' && \
     cd ..
 
 # Next.js collects completely anonymous telemetry data about general usage.
@@ -104,12 +123,14 @@ RUN cd ./contracts && \
 ENV NEXT_TELEMETRY_DISABLED=1
 
 RUN cd ./teesa && \
-  if [ -f yarn.lock ]; then yarn run build; \
-  elif [ -f package-lock.json ]; then npm run build; \
-  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
-  else echo "Lockfile not found." && exit 1; \
-  fi && \
-  cd ..
+    bash -c '\
+    . "/root/.nvm/nvm.sh" && \
+    if [ -f yarn.lock ]; then yarn run build; \
+    elif [ -f package-lock.json ]; then npm run build; \
+    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+    else echo "Lockfile not found." && exit 1; \
+    fi' && \
+    cd ..
 
 
 # Start stage
@@ -117,28 +138,26 @@ RUN cd ./teesa && \
 FROM base AS runner
 WORKDIR /app
 
+# Download and install Ollama
+RUN curl -fsSL https://ollama.com/install.sh | sh
+
 ENV NODE_ENV=production
 # Uncomment the following line in case you want to disable telemetry during runtime.
 ENV NEXT_TELEMETRY_DISABLED=1
 
-RUN addgroup --system --gid 1001 nodejs
-RUN adduser --system --uid 1001 nextjs
-
 # Copy the contracts files
-COPY --from=builder --chown=nextjs:nodejs /app/contracts ./contracts
+COPY --from=builder /app/contracts ./contracts
 
 # Copy the next.js build files
 COPY --from=builder /app/teesa/public ./teesa/public
 # Automatically leverage output traces to reduce image size
 # https://nextjs.org/docs/advanced-features/output-file-tracing
-COPY --from=builder --chown=nextjs:nodejs /app/teesa/.next/standalone ./teesa 
-COPY --from=builder --chown=nextjs:nodejs /app/teesa/.next/static ./teesa/.next/static
+COPY --from=builder /app/teesa/.next/standalone ./teesa 
+COPY --from=builder /app/teesa/.next/static ./teesa/.next/static
 
 # Copy and setup start script
 COPY deploy/start.sh ./
 RUN chmod +x start.sh
-
-USER nextjs
 
 EXPOSE 3000
 
